In [14]:
import numpy as np

# Через правые сингулярные векторы
def svd_decomposition(A):
    ATA = np.dot(A.T, A)

    eigenval, eigenvec = np.linalg.eig(ATA)
    singular = np.sqrt(eigenval)

    S = np.zeros(shape=(len(singular), len(singular)))
    for i in range(len(S)):
        S[i][i] = singular[i]
    V = eigenvec
    U = A @ V @ np.linalg.inv(S)

    return U, S, V.T

In [19]:
A = np.array([[3, 1, 0], [1, 2, 2], [0, 1, 1]])

print(f"A: {A}")

U, S, V_T = svd_decomposition(A)

A_compute = U @ S @ V_T

print(f"A_compute: {A_compute}")

print("----------------\n")

print(f"U: {U}")
print(f"S: {S}")
print(f"V_T: {V_T}")

print("----------------\n")

U_np, S_np, V_np = np.linalg.svd(A)
print(f"U_np: {U_np}")
print(f"S_np: {S_np}")
print(f"V_np: {V_np}")


print("ort")
for i in range(len(U)):
    for j in range(i + 1, len(U)):
        print(np.dot(U[i], U[j]))
        print(np.dot(V_T[i], V_T[j]))

A: [[3 1 0]
 [1 2 2]
 [0 1 1]]
A_compute: [[ 3.00000000e+00  1.00000000e+00 -1.75207071e-16]
 [ 1.00000000e+00  2.00000000e+00  2.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  1.00000000e+00]]
----------------

U: [[-0.67988662 -0.71823656 -0.14795412]
 [-0.68742382  0.55397543  0.46963786]
 [-0.25534813  0.42100768 -0.8703734 ]]
S: [[3.92823172 0.         0.        ]
 [0.         2.35739994 0.        ]
 [0.         0.         0.10798654]]
V_T: [[-0.69422679 -0.58807183 -0.41499481]
 [-0.67902533  0.34390515  0.64857834]
 [ 0.2386918  -0.73205244  0.63806383]]
----------------

U_np: [[-0.67988662  0.71823656  0.14795412]
 [-0.68742382 -0.55397543 -0.46963786]
 [-0.25534813 -0.42100768  0.8703734 ]]
S_np: [3.92823172 2.35739994 0.10798654]
V_np: [[-0.69422679 -0.58807183 -0.41499481]
 [ 0.67902533 -0.34390515 -0.64857834]
 [-0.2386918   0.73205244 -0.63806383]]
ort
1.3322676295501878e-15
-3.3306690738754696e-16
-1.1657341758564144e-15
3.3306690738754696e-16
2.3897550605056495e-14
-1