In [200]:
import numpy as np

In [201]:
def gerchgorin_circles(A):
    circles = []
    intervals = []
    p = 0
    for i in range(len(A)):
        center = A[i][i]
        radius = sum(abs(A[i][j]) for j in range(len(A)) if j != i)
        intervals.append([center - radius, center + radius])
        circles.append((center, radius))

    intervals.sort(key=lambda x:x[0])
    circles.sort(key=lambda x:x[0])
    merged = [intervals[0]]
    for i in range(1, len(intervals)):
        current_interval = intervals[i]
        previous_interval = merged[-1]
        if current_interval[0] <= previous_interval[1]:
            merged[-1] = [previous_interval[0], max(previous_interval[1], current_interval[1])]
            p += 1
        else:
            merged.append(current_interval)

    return intervals, p, circles

In [202]:
A = np.random.uniform(low=-10, high=10, size=(3, 3))
intervals, p, circles = gerchgorin_circles(A)
print(A)
print(circles)
print(intervals)
print(p)

[[ 6.60344867 -3.24374277  2.16898273]
 [-8.86724011  6.21569509 -3.08859403]
 [-3.11626008 -2.43852598 -9.53123681]]
[(-9.531236808832983, 5.554786060068921), (6.215695088741455, 11.95583414230071), (6.60344867475558, 5.412725496633049)]
[[-15.086022868901903, -3.9764507487640612], [-5.740139053559254, 18.171529231042165], [1.1907231781225303, 12.016174171388629]]
2


In [203]:
def svd_decomposition(A):
    ATA = np.dot(A.T, A)

    eigenval, eigenvec = np.linalg.eig(ATA)
    singular = np.sqrt(eigenval)

    S = np.zeros(shape=(len(singular), len(singular)))
    for i in range(len(S)):
        S[i][i] = singular[i]
    V = eigenvec
    U = A @ V @ np.linalg.inv(S)

    return U, S, V.T

_, S, _ = svd_decomposition(A)


circles = []


for i in range(len(S)):
    c = A[i][i]
    r = sum(abs(S[j][j]) for j in range(len(S)) if j != i)
    circles.append((c, r))
print(circles)


[(6.60344867475558, 9.76161746328736), (6.215695088741455, 23.476064301876796), (-9.531236808832983, 15.394955605799813)]
