In [4]:
import numpy as np

def svd_decomposition(A):
    ATA = np.dot(A.T, A)

    eigenval, eigenvec = np.linalg.eig(ATA)
    singular = np.sqrt(eigenval)

    S = np.zeros(shape=(len(singular), len(singular)))
    for i in range(len(S)):
        S[i][i] = singular[i]
    V = eigenvec
    U = A @ V @ np.linalg.inv(S)

    return U, S, V.T


In [5]:
A = np.array([[3, 1, 0], [1, 2, 2], [0, 1, 1]])

print(f"A: {A}")

U, S, V_T = svd_decomposition(A)

A_compute = U @ S @ V_T

print(f"A_compute: {A_compute}")

print("----------------\n")

print(f"U: {U}")
print(f"S: {S}")
print(f"V_T: {V_T}")

print("----------------\n")

U_np, S_np, V_np = np.linalg.svd(A)
print(f"U_np: {U_np}")
print(f"S_np: {S_np}")
print(f"V_np: {V_np}")

A: [[3 1 0]
 [1 2 2]
 [0 1 1]]
A_compute: [[ 3.00000000e+00  1.00000000e+00 -1.75207071e-16]
 [ 1.00000000e+00  2.00000000e+00  2.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  1.00000000e+00]]
----------------

U: [[-0.67988662 -0.71823656 -0.14795412]
 [-0.68742382  0.55397543  0.46963786]
 [-0.25534813  0.42100768 -0.8703734 ]]
S: [[3.92823172 0.         0.        ]
 [0.         2.35739994 0.        ]
 [0.         0.         0.10798654]]
V_T: [[-0.69422679 -0.58807183 -0.41499481]
 [-0.67902533  0.34390515  0.64857834]
 [ 0.2386918  -0.73205244  0.63806383]]
----------------

U_np: [[-0.67988662  0.71823656  0.14795412]
 [-0.68742382 -0.55397543 -0.46963786]
 [-0.25534813 -0.42100768  0.8703734 ]]
S_np: [3.92823172 2.35739994 0.10798654]
V_np: [[-0.69422679 -0.58807183 -0.41499481]
 [ 0.67902533 -0.34390515 -0.64857834]
 [-0.2386918   0.73205244 -0.63806383]]


In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"A: {A}")

U, S, V_T = svd_decomposition(A)

A_compute = U @ S @ V_T

print(f"A_compute: {A_compute}")

print("----------------\n")

print(f"U: {U}")
print(f"S: {S}")
print(f"V_T: {V_T}")

print("----------------\n")

U_np, S_np, V_np = np.linalg.svd(A)
print(f"U_np: {U_np}")
print(f"S_np: {S_np}")
print(f"V_np: {V_np}")

A: [[1 2 3]
 [4 5 6]
 [7 8 9]]
A_compute: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
----------------

U: [[-2.14837238e-01  8.87230688e-01  8.66671290e-08]
 [-5.20587389e-01  2.49643953e-01  2.88890430e-08]
 [-8.26337541e-01 -3.87942782e-01 -2.16667823e-08]]
S: [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.14889472e-08]]
V_T: [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]
----------------

U_np: [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
S_np: [1.68481034e+01 1.06836951e+00 4.41842475e-16]
V_np: [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [7]:
A = np.array([[1, 2], [4, 5], [7, 8]])

print(f"A: {A}")

U, S, V_T = svd_decomposition(A)

A_compute = U @ S @ V_T

print(f"A_compute: {A_compute}")

print("----------------\n")

print(f"U: {U}")
print(f"S: {S}")
print(f"V_T: {V_T}")

print("----------------\n")

U_np, S_np, V_np = np.linalg.svd(A)
print(f"U_np: {U_np}")
print(f"S_np: {S_np}")
print(f"V_np: {V_np}")

A: [[1 2]
 [4 5]
 [7 8]]
A_compute: [[1. 2.]
 [4. 5.]
 [7. 8.]]
----------------

U: [[ 0.89640564 -0.17259857]
 [ 0.27400657 -0.50818671]
 [-0.3483925  -0.84377485]]
S: [[ 0.58339625  0.        ]
 [ 0.         12.59601718]]
V_T: [[-0.76502988  0.64399479]
 [-0.64399479 -0.76502988]]
----------------

U_np: [[-0.17259857  0.89640564  0.40824829]
 [-0.50818671  0.27400657 -0.81649658]
 [-0.84377485 -0.3483925   0.40824829]]
S_np: [12.59601718  0.58339625]
V_np: [[-0.64399479 -0.76502988]
 [-0.76502988  0.64399479]]


In [10]:
A = np.array([[2, 3, -8], [4, 5, -11]])

print(f"A: {A}")

U, S, V_T = svd_decomposition(A)

A_compute = U @ S @ V_T

print(f"A_compute: {A_compute}")

print("----------------\n")

print(f"U: {U}")
print(f"S: {S}")
print(f"V_T: {V_T}")

print("----------------\n")

U_np, S_np, V_np = np.linalg.svd(A)
print(f"U_np: {U_np}")
print(f"S_np: {S_np}")
print(f"V_np: {V_np}")

A: [[  2   3  -8]
 [  4   5 -11]]
A_compute: [[  2.   3.  -8.]
 [  4.   5. -11.]]
----------------

U: [[-5.66758674e-01  8.23883854e-01 -1.97633093e-07]
 [-8.23883854e-01 -5.66758674e-01  1.79666449e-08]]
S: [[1.54388506e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.01181200e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.47174257e-08]]
V_T: [[-0.2868771  -0.37695133  0.88068679]
 [-0.77294249 -0.45200987 -0.44524936]
 [-0.56591646  0.80845208  0.16169042]]
----------------

U_np: [[-0.56675867  0.82388385]
 [-0.82388385 -0.56675867]]
S_np: [15.43885063  0.8011812 ]
V_np: [[-0.2868771  -0.37695133  0.88068679]
 [-0.77294249 -0.45200987 -0.44524936]
 [ 0.56591646 -0.80845208 -0.16169042]]
